### ISSUE TITLE
repl file is missing

### ISSUE THREAD

**Issue by alejandro** [matthewrobb/six#47]
Probably I'm missing something here but when I tried to run `six`  I get:

``` bash
module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/lib/node_modules/six/lib/repl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.exports.run (/usr/lib/node_modules/six/lib/command.js:128:12)
    at Object.<anonymous> (/usr/local/bin/si:8:30)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

But there is not a `repl` file inside lib or in the repo at all. Specially [here (L119)](https://github.com/matthewrobb/six/blob/master/lib/command.js#L119) and [here (L128)](https://github.com/matthewrobb/six/blob/master/lib/command.js#L128)

Any hints?

Thanks.

/be

**Comment by alejandro** [comment]
Closing this, not implemented.
