### ISSUE TITLE
Destructuring

### ISSUE THREAD

**Issue by matthewrobb** [matthewrobb/six#7]
http://wiki.ecmascript.org/doku.php?id=harmony:destructuring

**Comment by SlexAxton** [comment]
The examples on the README imply that destructuring is already supported. This issue (and my test run) seem to imply that it is not. Can we clarify in the readme which features aren't ready yet?

Thanks!

**Comment by matthewrobb** [comment]
I'm going to be spending a great deal of time improving documentation here in the next few weeks, I just had a new baby and am preparing to move from the Boston area to the Seattle area so my time has been very limited.

**Comment by matthewrobb** [comment]
The browser script is not up to date with the master branch including the demo. What is supported is object destructuring in variable declarations.

``` javascript
var { a } = b;
```

**Comment by SlexAxton** [comment]
In my attempts with checking out master:

``` javascript
var [ x, y ] = "15,13".split(',');
console.log(x, y);
```

When run with six:

``` sh
> six test.six.js
TypeError: Cannot read property '0' of undefined
    at Tree.raw (/Users/alex.sexton/Code/six/lib/esom/tree.js:85:52)
    at Tree.Object.define.compile (/Users/alex.sexton/Code/six/lib/rewriter.js:30:25)
    at Array.forEach (native)
    at Tree.Object.define.compile (/Users/alex.sexton/Code/six/lib/rewriter.js:29:31)
    at Tree.Object.define.compile (/Users/alex.sexton/Code/six/lib/rewriter.js:33:47)
    at Array.forEach (native)
    at Tree.Object.define.compile (/Users/alex.sexton/Code/six/lib/rewriter.js:29:31)
    at Tree.Object.define.compile (/Users/alex.sexton/Code/six/lib/rewriter.js:33:47)
    at Array.forEach (native)
    at Tree.Object.define.compile (/Users/alex.sexton/Code/six/lib/rewriter.js:29:31)
```

**Comment by SlexAxton** [comment]
Here is the same code in Firefox stable, for reference:

![http://f.cl.ly/items/2e2Y1s3O2G46180X0n3b/Screen%20Shot%202012-10-30%20at%2012.52.18%20AM.png](http://f.cl.ly/items/2e2Y1s3O2G46180X0n3b/Screen%20Shot%202012-10-30%20at%2012.52.18%20AM.png)

**Comment by matthewrobb** [comment]
Yeah ArrayPattern rewriting is not currently implemented.

**Comment by SlexAxton** [comment]
Cool. Should we close this issue and open up a specific ArrayPattern issue? I'd love to get involved.

**Comment by matthewrobb** [comment]
This issue just represents general feature support, I'm not planning on closing it until the implementation is functionally complete.

**Comment by matthewrobb** [comment]
Any help would definitely be appreciated, quite a bit of road to go before things are where they need to go.
